/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package array_form_netbeans;

/**
 *
 * @author Lenovo
 */
public class pemiihan_dokter extends javax.swing.JFrame {

    /**
     * Creates new form pemiihan_dokter
     */
    public pemiihan_dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pilihdokter1 = new javax.swing.JLabel();
        pilihdokter2 = new javax.swing.JLabel();
        box = new javax.swing.JComboBox<>();
        spesialis1 = new javax.swing.JTextField();
        nama1 = new javax.swing.JTextField();
        alamat1 = new javax.swing.JTextField();
        usia1 = new javax.swing.JTextField();
        jenis1 = new javax.swing.JTextField();
        gol1 = new javax.swing.JTextField();
        status1 = new javax.swing.JTextField();
        kewar1 = new javax.swing.JTextField();
        waktu1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 180, 22);

        pilihdokter1.setText("Pilih Dokter ");
        getContentPane().add(pilihdokter1);
        pilihdokter1.setBounds(50, 60, 80, 14);

        pilihdokter2.setText("Identitas");
        getContentPane().add(pilihdokter2);
        pilihdokter2.setBounds(50, 90, 80, 14);

        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "DR. Farras Yassar", "DR. Dian Sikahita", "DR. Harun Ulum Fajar" }));
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        getContentPane().add(box);
        box.setBounds(140, 60, 110, 20);

        spesialis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesialis1ActionPerformed(evt);
            }
        });
        getContentPane().add(spesialis1);
        spesialis1.setBounds(190, 380, 170, 20);
        getContentPane().add(nama1);
        nama1.setBounds(190, 120, 170, 20);

        alamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat1ActionPerformed(evt);
            }
        });
        getContentPane().add(alamat1);
        alamat1.setBounds(190, 160, 170, 20);

        usia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usia1ActionPerformed(evt);
            }
        });
        getContentPane().add(usia1);
        usia1.setBounds(190, 190, 170, 20);

        jenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis1ActionPerformed(evt);
            }
        });
        getContentPane().add(jenis1);
        jenis1.setBounds(190, 220, 170, 20);

        gol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gol1ActionPerformed(evt);
            }
        });
        getContentPane().add(gol1);
        gol1.setBounds(190, 250, 170, 20);

        status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1ActionPerformed(evt);
            }
        });
        getContentPane().add(status1);
        status1.setBounds(190, 280, 170, 20);

        kewar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kewar1ActionPerformed(evt);
            }
        });
        getContentPane().add(kewar1);
        kewar1.setBounds(190, 310, 170, 20);

        waktu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktu1ActionPerformed(evt);
            }
        });
        getContentPane().add(waktu1);
        waktu1.setBounds(190, 360, 170, 20);

        jLabel2.setText("Dokter Spesialis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 380, 100, 14);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 27, 14);

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 34, 14);

        jLabel5.setText("Usia");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 34, 14);

        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 70, 14);

        jLabel7.setText("Golongan Darah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 250, 100, 14);

        jLabel8.setText("Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 280, 100, 14);

        jLabel9.setText("Kewarganegaraan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 310, 100, 14);

        jLabel10.setText("Waktu Praktek");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 360, 100, 14);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 460);

        setBounds(0, 0, 428, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
        if(box.getSelectedItem().equals("DR. Farras Yassar")){
            nama1.setText("DR. Farras Yassar ");
            alamat1.setText("Jl. Surabaya 16, Malang");
            usia1.setText("20 Tahun");
            jenis1.setText("Laki-Laki");
            gol1.setText("A");
            status1.setText("Belum Menikah ");
            kewar1.setText("Indonesia");
            spesialis1.setText("Dokter Umum");
            waktu1.setText(" Pagi (07.00-15.00)");
        }
        else
            if(box.getSelectedItem().equals("DR. Dian Sikahita")){
            nama1.setText("DR. Dian Sikahita");
            alamat1.setText("Jl. Veteran 3, Malang");
            usia1.setText("20 Tahun");
            jenis1.setText("Perempuan");
            gol1.setText("O");
            status1.setText("Belum Menikah");
            kewar1.setText("Indonesia");
            spesialis1.setText("Dokter Gigi");
            waktu1.setText(" Sore (16.00-22.00)");
        }
        else
               if(box.getSelectedItem().equals("DR. Harun Ulum Fajar")){
            nama1.setText("DR. Harun Ulum Fajar");
            alamat1.setText("Jl. Bandung 9, Malang");
            usia1.setText("20 Tahun");
            jenis1.setText("Laki-Laki");
            gol1.setText("B");
            status1.setText("Belum Menikah");
            kewar1.setText("Indonesia");
            spesialis1.setText("Dokter Gizi");
            waktu1.setText(" Malam (22.00-06.00)");
        }
     

    }//GEN-LAST:event_boxActionPerformed

    private void spesialis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesialis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spesialis1ActionPerformed

    private void alamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat1ActionPerformed

    private void usia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usia1ActionPerformed

    private void jenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis1ActionPerformed

    private void gol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gol1ActionPerformed

    private void status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status1ActionPerformed

    private void kewar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kewar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kewar1ActionPerformed

    private void waktu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemiihan_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemiihan_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemiihan_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemiihan_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemiihan_dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat1;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JTextField gol1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenis1;
    private javax.swing.JTextField kewar1;
    private javax.swing.JTextField nama1;
    private javax.swing.JLabel pilihdokter1;
    private javax.swing.JLabel pilihdokter2;
    private javax.swing.JTextField spesialis1;
    private javax.swing.JTextField status1;
    private javax.swing.JTextField usia1;
    private javax.swing.JTextField waktu1;
    // End of variables declaration//GEN-END:variables
}
